### ISSUE TITLE
GitHub action not using global configuration

### ISSUE THREAD

**Issue by tombeteende** [The-PR-Agent/pr-agent#1666]
### Git provider

Github Cloud

### System Info

I am running in the GitHub cloud, using GitHub standard runners. I am trying to set global configuration across my organization where both repositories are internal, and global configuration is not fetched as expected.

### Bug details

Following the instruction [here](https://qodo-merge-docs.qodo.ai/usage-guide/configuration_options/#global-configuration-file)
I created a repository called `pr-agent-settings` with a configuration file that looks like this -

```
[config]
model = "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
model_turbo = "bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"
fallback_models = "bedrock/anthropic.claude-3-sonnet-20240229-v1:0"

[litellm]
drop_params = true
```

In another repository, I have the github action below. When I look in the logs, I see that the review process tried to use OpenAI models (and failed since no API key was given) instead of fetching the configuration from `pr-agent-settings`.

What am I missing? Do I need to set anything else?
Both repositories are internal
Is there additional documentation regarding global settings?

```
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

permissions:
  id-token: write   # This is required for requesting the JWT
  issues: write
  pull-requests: write
  contents: write


jobs:
  assume-aws-role: <...>

  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    needs: [assume-aws-role]
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
