### ISSUE TITLE
Github Actions reports in log error 429 RateLimitError invoking OpenAI but action succeeds

### ISSUE THREAD

**Issue by huksley** [The-PR-Agent/pr-agent#1678]
### Git provider

Github Cloud

### System Info

pr-agent v.0.28 commit hash 7d57edf959473b164a185c5585e9ec9bbcb9213f

## Bugs
 
1. In the log there is a message "Error during LLM inference: litellm.RateLimitError: RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}\n", "record": {"elapsed": {"repr": "0:00:32.160645", "seconds": 32.160645}, "exception": null, "extra": {}, "file": {"name": "litellm_ai_handler.py", "path": "/app/pr_agent/algo/ai_handlers/litellm_ai_handler.py"}, "function": "chat_completion", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 319, "message": "Error during LLM inference: litellm.RateLimitError: RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guid"
 
2. Github Action succeeds!!! with message "Failed to generate code suggestions for PR"

## Expectation

If it fails it should report error in github actions, not success! 

It looks like it does not use OpenAI api key - OpenAI platform reports no api key usage.

## Github Actions workflow

OPENAI_KEY is defined in secrets.

```yaml
name: "Pull Request Agent"
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr-agent:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        # https://github.com/qodo-ai/pr-agent/tags - v0.28 - 7d57edf959473b164a185c5585e9ec9bbcb9213f
        uses: qodo-ai/pr-agent@7d57edf959473b164a185c5585e9ec9bbcb9213f
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
